# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('harddisk', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('cpu_cores', models.IntegerField()),
                ('instance', models.CharField(max_length=250)),
            ],
        ),
    ]
